inugami:
  release:
    management:
      domain:
        version:
          defaultPageSize: 50
        cve:
          importer:
            maxThreads: 20
            timeout: 30000
            mitre:
              folder.temp: "${user.home}/.inugami/inugami_cve_importer_mitre"
              maxThreads: 20
              timeout: 30000

spring:
  data:
    neo4j:
      username: neo4j
      password: password